### ISSUE TITLE
Create GUI

### ISSUE THREAD

**Issue by hjed** [bluesat/owr_software#28]
We need a full GUI for controlling the robot, including GPS data and cameras.
Suggestions include using inbuilt ROS gui library and using android tablets (more portable).

**Comment by sbt-tbs** [comment]
Suggested feature:
Mark route taken on map with colour code for angle off terrain.  Near level one colour and other colour(s) for more steep terrain.

**Comment by sbt-tbs** [comment]
Move button code into class to clean up global namespace.
