### ISSUE TITLE
Get camera feed playback working

### ISSUE THREAD

**Issue by sbt-tbs** [bluesat/owr_software#51]

**Comment by hjed** [comment]
hm, the gstreamer command here does not work for me

**Comment by hjed** [comment]
Actually it does half the time... (may be a virtuabox issue)

**Comment by hjed** [comment]
For now let just use this:
on the robot side:
roscd gscam
cd bin
export GSCAM_CONFIG="v4l2src device=/dev/video2 ! video/x-raw-rgb,framerate=30/1 ! ffmpegcolorspace"
rosrun gscam gscam

and on the groundstation side
rosrun image_view image_view image:=/camera/image_raw

**Comment by hjed** [comment]
changing the framerate seems to break it
