### ISSUE TITLE
Design Fine Sensing & Control GUI

### ISSUE THREAD

**Issue by sbt-tbs** [bluesat/owr_software#59]

**Comment by hjed** [comment]
![img_20150425_135726](https://cloud.githubusercontent.com/assets/6956262/7331514/5b3a91d4-eb55-11e4-933b-5c3c1c97b312.jpg)
![img_20150425_135730](https://cloud.githubusercontent.com/assets/6956262/7331515/5b3a9c4c-eb55-11e4-895a-80595f210435.jpg)
